### PR TITLE
Check alternative names before common name

### PR DESCRIPTION
**Pull request by pbrisbin**
This reverses the logic to check SAN values if present. Previously, CN
was checked first and caused a NoCommonName failure immediately when not
present.

As per RFC [6125][1], the validator must check SAN first, and if SAN
exists, then CN should not be checked.

[1]: https://tools.ietf.org/html/rfc6125#section-6.4.4

--

See #47 -- this gets things working in that case. I don't have much crypto experience, so I very much could've overlooked something. I open this PR to start the discussion, not as a proposal of what I'm sure is the right fix.

I've bumped the version so I can reference it in my own cabal file -- let me know if I should revert that, or bump it to something else.

### CODE REVIEW

**Comment by vincenthz** [comment]
Sorry I'm a bit slow, but that looks good. Can you remove the cabal versioning update though, as it doesn't play nice with how I sign and release package to hackage

**Comment by pbrisbin** [comment]
Absolutely, will do soon.

**Comment by pbrisbin** [comment]
All set

**Comment by vincenthz** [comment]
excellent ! very fast too ;)

**Comment by vincenthz** [comment]
will try to make a release sometimes tomorrow. don't hesitate to prod me if it doesn't appear on hackage

**Comment by pbrisbin** [comment]
That'd be awesome. Thanks!

**Comment by pbrisbin** [comment]
Hi. It doesn't look like this has been released yet.

**Comment by vincenthz** [comment]
sorry about this, has been released as x509-validation-1.5.2

**Pull request merged**
