### PR TITLE
EC private keys

### PR DESCRIPTION
**Pull request by ocheron**
This adds support for EC private keys (in named and explicit formats) and PEM-parsing tests for each key/certificate type.

The PR contains a new exposed module `Data.X509.EC` because I needed to get the curve OID table from x509 in x509-store.  I also added here some utility functions that should help reduce code duplication in x509-* and tls (point deserialization, explicit prime curve handling).

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
:+1:

**Comment by ocheron** [comment]
I'll also mention that adding ECDSA signing may not be the best idea, as the pure-Haskell implementation in cryptonite is not time constant. My main goal is enabling ECDSA key exchange in `tls` test suite but not necessarily everywhere.

**Comment by wangbj** [comment]
Is reading parsing RSA private key supported already?

**Comment by ocheron** [comment]
Yes package x509-store has functions to read RSA private keys from file or memory.

**Comment by ocheron** [comment]
Thanks @vincenthz.

So that means we can add server ECDHE_ECDSA and test more ciphersuites in tls.
Do you guys think this is something to enable by default or keep disabled?
Prerequisite is to configure an ECDSA certificate anyway.

**Pull request merged**
